/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.5.v201512091508.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COM_MATEUSZMIDOR_Calc_STUB_HPP_
#define V1_COM_MATEUSZMIDOR_Calc_STUB_HPP_

#include <functional>




#include <v1/com/mateuszmidor/Calc.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <unordered_set>
#include <vector>

#include <CommonAPI/Stub.hpp>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1 {
namespace com {
namespace mateuszmidor {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service Calc. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class CalcStubAdapter
    : public virtual CommonAPI::StubAdapter, 
      public virtual Calc {
 public:

    /**
     * Sends a broadcast event for calculationDone. Should not be called directly.
     * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
     */
    virtual void fireCalculationDoneEvent(const std::string &_msg) = 0;


    virtual void deactivateManagedInstances() = 0;
protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */
};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for Calc.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class CalcStubRemoteEvent
{
public:
    virtual ~CalcStubRemoteEvent() { }

};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service Calc to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class CalcStub
    : public virtual CommonAPI::Stub<CalcStubAdapter, CalcStubRemoteEvent>
{
public:
    typedef std::function<void (int64_t _result)>addReply_t;

    virtual ~CalcStub() {}
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> clientId) = 0;


    /// This is the method that will be called on remote calls on the method add.
    virtual void add(const std::shared_ptr<CommonAPI::ClientId> _client, int32_t _a, int32_t _b, addReply_t _reply) = 0;
    /// Sends a broadcast event for calculationDone.
    virtual void fireCalculationDoneEvent(const std::string &_msg) = 0;

    using CommonAPI::Stub<CalcStubAdapter, CalcStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<CalcStubAdapter, CalcStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<CalcStubAdapter, CalcStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef CalcStubRemoteEvent RemoteEventType;
    typedef Calc StubInterface;
};

} // namespace mateuszmidor
} // namespace com
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COM_MATEUSZMIDOR_Calc_STUB_HPP_
