FROM ubuntu:15.10
RUN apt-get update -y
RUN apt-get install -y openjdk-8-jdk
ENV PATH /usr/bin/$PATH

#WORKDIR /path/to/workdir # set cwd for ADD, COPY, RUN Dockerfile commands
#ADD ["<src>",... "<dest>"] # add src file under WORKDIR/dst in image
#USER mateusz # set user to be used 
